name: oSuffixes
version: '1.1'
main: me.oz1p.osuffixes.OSuffixes
api-version: '1.16'
depend: [PlaceholderAPI]
authors: [Oz1p]
description: Simple plugin for Suffixes
commands:
  oSuffixes:
    aliases: os
    usage: /osuffixes
